<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/layui/2.6.8/css/layui.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/layui/2.6.8/layui.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.8/vue.min.js"></script>
</head>
<style type="text/css">
body {
  background-color: #F4F5F6;
  margin: 0;
  padding: 0;
}

.layui-container {
  margin-top: 50px;
  width: 80vw;
  line-height: 40px;
}

.layui-table {
  margin: 0;
  width: 100%;
  table-layout: fixed;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI Adjusted", "Segoe UI", "Liberation Sans", sans-serif;
}

.layui-table ol li {
  list-style: decimal;
  margin-left: 30px;
}

.layui-table td {
  padding: 5px 15px;
  font-size: 14px;
  color: #232629;
  line-height: 20px;
  border: none;
  border-bottom: 0px solid #FFFFFF;
}

.layui-table a {
  font-size: 14px;
  line-height: 20px;
}

.layui-table .left-font {
  text-align: right;
  vertical-align: top;
  font-size: 15px;
  background-color: #F2F3F4;
}

.layui-table[lay-even] tr:nth-child(even) {
  background-color: #F2F3F4;
}

.layui-table[lay-even] tr:nth-child(odd) {
  background-color: #F2F3F4;
}

.layui-panel {
  font-size: 12px;
  color: #232629;
  margin: 10px 0 50px;
  padding: 9px 0;
  background-color: #F2F3F4;
}

.layui-panel a:hover {
  color: #3B4045;
}

.layui-panel .title {
  padding: 5px;
  font-size: 25px;
  line-height: 40px;
  margin: 0 20px 0;
  color: #3B4045;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI Adjusted", "Segoe UI", "Liberation Sans", sans-serif;
}

/*mark {*/
/*    background-color: #F0B27A;*/
/*    padding: 1px 3px 1px;*/
/*    border-radius: 3px;*/
/*    line-height: 16px;*/
/*    margin: 0 1px;*/
/*}*/

/*em {*/
/*    font-family: Georgia, Cambria, "Times New Roman", Times, serif;*/
/*    font-size: 15px;*/
/*    margin: 0 5px;*/
/*    text-decoration: underline;*/
/*}*/

/*.layui-table ol li mark {*/
/*    background-color: #CACFD2;*/
/*}*/

code {
  font-family: ui-monospace, "Cascadia Mono", "Segoe UI Mono", "Liberation Mono", Menlo, Monaco, Consolas, monospace;
  font-size: 12px;
  border-radius: 3px;
  line-height: 20px;
  word-wrap: normal;
}

pre {
  padding: 12px;
  width: auto;
  overflow: auto;
  background-color: #E7E8E9;
  border-radius: 3px;
}

.answer-title a {
  font-size: 18px;
  font-weight: bold;
}
</style>

<body>
  <div id="app" class="layui-container">
    <div class="layui-row layui-col-space15">
      <div class="layui-col-md12">
        <div class="layui-panel" style="margin-bottom: 30px;">
          <div class="title"><strong>Query:&nbsp;&nbsp;</strong>
            <a :href="'https://stackoverflow.com/questions/'+post_id" target="_blank" v-html="title">
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="layui-panel" v-for="(answer, index) in answer">
      <table class="layui-table" lay-even>
        <colgroup>
          <col width="14%">
          <col width="86%">
        </colgroup>
        <tbody>
          <tr>
            <td rowspan="1" class="left-font">
              <strong>Id&nbsp;[<span>{{answer.answer_id}}</span>]</strong>
            </td>
            <td>
              <div class="answer-title">
                <a :href="'https://stackoverflow.com/questions/'+answer.answer_id" target="_blank" v-html="answer.title">
                </a>
              </div>
            </td>
          </tr>
          <tr>
            <td rowspan="1" class="left-font">
              <strong>Environment</strong>
            </td>
            <td>
              <strong>{{answer.environment.join(", ")}}</strong>
            </td>
          </tr>
          <tr>
            <td rowspan="1" class="left-font">
              <strong>Extra Info</strong>
            </td>
            <td>
              <span class="layui-badge layui-bg-black">ViewCount:&nbsp;{{answer.ViewCount}}</span>
              <span class="layui-badge layui-bg-black">Score:&nbsp;{{answer.Score}}</span>
              <span class="layui-badge layui-bg-black">AnswerScore:&nbsp;{{answer.AnswerScore}}</span>
              <span class="layui-badge layui-bg-black">Environment Score:&nbsp;{{answer.environment_score}}</span>
              <span v-show="answer.exception_message_score" class="layui-badge layui-bg-black">Exception Message Score:&nbsp;{{answer.exception_message_score}}</span>
              <span v-show="answer.exception_stack_score" class="layui-badge layui-bg-black">Exception Stack
                Score:&nbsp;{{answer.exception_stack_score}}</span>
              <span v-show="answer.code_score" class="layui-badge layui-bg-black">Code
                Score:&nbsp;{{answer.code_score}}</span>
              <span v-show="answer.symptom_score" class="layui-badge layui-bg-black">Symptom
                Score:&nbsp;{{answer.symptom_score}}</span>
              <span v-show="answer.purpose_score" class="layui-badge layui-bg-black">Purpose
                Score:&nbsp;{{answer.purpose_score}}</span>
            </td>
          </tr>
          <!--          <tr>-->
          <!--            <td rowspan="1" class="left-font">-->
          <!--              <strong>Exception Stack</strong>-->
          <!--            </td>-->
          <!--            <td>-->
          <!--              <div v-for="(exc,) in answer.exception_stack">-->
          <!--                <pre style="max-height: 300px"><code>{{exc}}</code></pre>-->
          <!--              </div>-->
          <!--            </td>-->
          <!--          </tr>-->
          <tr v-show="answer.exception_message">
            <td rowspan="1" class="left-font">
              <strong>Exception Message</strong>
            </td>
            <td>
              <div>
                <pre style="max-height: 300px"><code>{{answer.exception_message}}</code></pre>
              </div>
            </td>
          </tr>
          <tr v-show="answer.symptom">
            <td rowspan="1" class="left-font">
              <strong>Symptom</strong>
            </td>
            <td>
              <p v-for="(symptom,) in answer.symptom">{{symptom}}</p>
            </td>
          </tr>
          <tr v-show="answer.code.length>0">
            <td rowspan="1" class="left-font">
              <strong></strong>
            </td>
            <td>
              <div class="layui-collapse">
                <div class="layui-colla-item" v-for="(code,i) in answer.code">
                  <h2 class="layui-colla-title">code {{i + 1}}</h2>
                  <pre class="layui-colla-content" style="max-height: 300px"><code>{{code}}</code></pre>
                </div>
              </div>
            </td>
          </tr>
          <tr v-show="answer.reason.length>0">
            <td rowspan="1" class="left-font">
              <strong>Reason</strong>
            </td>
            <td>
              <p v-for="(reason,) in answer.reason">{{reason}}</p>
            </td>
          </tr>
          <tr>
            <td rowspan="1" class="left-font">
              <strong>Solution</strong>
            </td>
            <td>
              <p v-for="(solution,) in answer.solution">{{solution}}</p>
            </td>
          </tr>
          <tr v-show="answer.answer_code.length>0">
            <td rowspan="1" class="left-font">
              <strong></strong>
            </td>
            <td>
              <div class="layui-collapse">
                <div class="layui-colla-item" v-for="(answer_code, i) in answer.answer_code">
                  <h2 class="layui-colla-title">code {{i + 1}}</h2>
                  <pre class="layui-colla-content" style="max-height: 600px"><code>{{answer_code}}</code></pre>
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <script type="text/javascript">
  const vm = new Vue({
    el: '#app',
    data: JSON.parse(JSON.stringify({"post_id": "5712783", "exception_type": "SocketException", "environment": "socketexception, tomcat, java", "title": "\"java.net.SocketException: Connection reset\" sometimes on Tomcat localhost log", "answer": [{"answer_id": "26628161", "title": "Tomcat 7 throwing frequent java.net.SocketException: Connection reset", "Score": 1, "ViewCount": 1853, "LastEditDate": "", "LastActivityDate": "2014-11-03 05:59:55", "AnswerScore": 2, "reason": ["More investigations and Wireshark dumps reveal, other than the actual load, 2 other things, show up, one is the load balancer which does a regular heartbeat check and another is a network monitoring script that again does a frequent pings. ", "So when we were monitoring a passive server which is again behind the LB and would too get pinged by the network monitoring script, but no production load. ", "It too showed up the same exceptions that we saw on the active server with load. "], "solution": ["So one we can either ignore these or alter the monitoring script to wait for the responses from the server. "], "answer_code": [], "environment": ["connection-reset", "tomcat 7", "java", "tomcat", "socketexception", "5 eof's", "server", "sockets"], "symptom": ["I am using Tomcat 7 and am getting frequent connection reset errors, -CODE-. and at times, though not frequently \"Unexpected EOF read on the socket\", -CODE-", "From what i have read through, both seem to indicate that the client might have possibly abruptly closed the connection, while the server is reading it, resulting into a reset and/or EOF. ", "Also if both exceptions originate from the same problem, how is the frequency so varied, i get about 100 connection resets to say 5 EOF's. "], "exception_stack": ["org.apache.coyote.http11.Http11Processor - Error parsing HTTP request header\n\njava.net.SocketException: Connection reset\n    at java.net.SocketInputStream.read(SocketInputStream.java:189)\n    at java.net.SocketInputStream.read(SocketInputStream.java:121)\n    at org.apache.coyote.http11.InternalInputBuffer.fill(InternalInputBuffer.java:516)\n    at org.apache.coyote.http11.InternalInputBuffer.fill(InternalInputBuffer.java:501)\n    at org.apache.coyote.http11.InternalInputBuffer.parseRequestLine(InternalInputBuffer.java:98)\n    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:931)\n    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)\n    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)\n    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)\n    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)\n    at java.lang.Thread.run(Thread.java:722)\n", "org.apache.coyote.http11.Http11Processor - Error parsing HTTP request header\n\njava.io.EOFException: Unexpected EOF read on the socket\n    at org.apache.coyote.http11.InternalInputBuffer.parseRequestLine(InternalInputBuffer.java:99)\n    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:931)\n    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)\n    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)\n    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)\n    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)\n    at java.lang.Thread.run(Thread.java:722)\n"], "code": [], "symptom_rank": 0, "environment_rank": 0, "exception_stack_rank": 22, "exception_message": "java.net.SocketException: Connection reset\n", "symptom_score": 100, "environment_score": 100, "exception_stack_score": 34}, {"answer_id": "585599", "title": "What's causing my java.net.SocketException: Connection reset?", "Score": 150, "ViewCount": 987994, "LastEditDate": "2019-01-24 12:39:20", "LastActivityDate": "2019-01-24 12:39:20", "AnswerScore": 66, "reason": ["In your case it seems that the connection has been closed by the server end of the connection. ", "This could be an issue with the request you are sending or an issue at their end. ", "If this was successful it could indicate a bug in the Java code. "], "solution": ["To aid debugging you could look at using a tool such as Wireshark to view the actual network packets. ", "Also, is there an alternative client to your Java code that you could use to test the web service. ", "As you are using Commons HTTP Client have a look at the Common HTTP Client Logging Guide. https://hc.apache.org/httpclient-legacy/logging.html", "This will tell you how to log the request at the HTTP level. "], "answer_code": ["\nThrown to indicate that there is an error in the underlying protocol such as a TCP error\n"], "environment": ["connection-reset", "tomcat", "socketexception", "java.net", "java", "sockets"], "symptom": ["We are seeing frequent but intermittent java.net.SocketException: Connection reset errors in our logs. ", "We are unsure as to where the Connection reset error is actually coming from, and how to go about debugging. ", "The issue appears to be unrelated to the messages we are attempting to send. ", "Note that the message is not connection reset by peer. ", "Here is a representative stack trace (com.companyname.mtix.sms is our component): -CODE-. ", "Our component is a web application, running under Tomcat, that calls a third party Web service that sends SMS messages, it so happens. ", "The line of our code on which the exception gets thrown from is the last line in the code snippet below. -CODE-"], "exception_stack": ["\n\n    java.net.SocketException: Connection reset\n        at java.net.SocketInputStream.read(SocketInputStream.java:168)\n        at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)\n        at java.io.BufferedInputStream.read(BufferedInputStream.java:235)\n        at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:77)\n        at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:105)\n        at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1115)\n        at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1832)\n        at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1590)\n        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:995)\n        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:397)\n        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)\n        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)\n        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)\n        at com.companyname.mtix.sms.services.impl.message.SendTextMessage.sendTextMessage(SendTextMessage.java:127)\n        at com.companyname.mtix.sms.services.MessageServiceImpl.sendTextMessage(MessageServiceImpl.java:125)\n        at com.companyname.mtix.sms.services.remote.MessageServiceRemoteImpl.sendTextMessage(MessageServiceRemoteImpl.java:43)\n        at sun.reflect.GeneratedMethodAccessor203.invoke(Unknown Source)\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\n        at java.lang.reflect.Method.invoke(Method.java:585)\n        at org.apache.axis.providers.java.RPCProvider.invokeMethod(RPCProvider.java:397)\n        at org.apache.axis.providers.java.RPCProvider.processMessage(RPCProvider.java:186)\n        at org.apache.axis.providers.java.JavaProvider.invoke(JavaProvider.java:323)\n        at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)\n        at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)\n        at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)\n        at org.apache.axis.handlers.soap.SOAPService.invoke(SOAPService.java:453)\n        at org.apache.axis.server.AxisServer.invoke(AxisServer.java:281)\n        at org.apache.axis.transport.http.AxisServlet.doPost(AxisServlet.java:699)\n        at javax.servlet.http.HttpServlet.service(HttpServlet.java:709)\n        at org.apache.axis.transport.http.AxisServletBase.service(AxisServletBase.java:327)\n        at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)\n        at com.companyname.mtix.sms.http.filters.NoCacheFilter.doFilter(NoCacheFilter.java:63)\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)\n        at com.companyname.mtix.sms.http.filters.MessageFilter.doFilter(MessageFilter.java:53)\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)\n        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:61)\n        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:77)\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)\n        at org.ajaxanywhere.AAFilter.doFilter(AAFilter.java:46)\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)\n        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)\n        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)\n        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)\n        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)\n        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:541)\n        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)\n        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)\n        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)\n        at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)\n        at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)\n        at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)\n        at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)\n        at java.lang.Thread.run(Thread.java:595)\n    "], "code": ["String aggregatorResponse = null;\nHttpClient httpClient = prepareHttpClient( username, password );\nPostMethod postMethod = preparePostMethod( textUrl );\n\ntry {\n  SybaseTextMessageBuilder builder = new SybaseTextMessageBuilder();\n  URL notifyUrl = buildNotificationUrl( textMessage, codeSetManager );\n  String smsRequestDocument = builder.buildTextMessage( textMessage, notifyUrl );\n  LOG.debug( \"Sybase MT document created as: \\n\" + smsRequestDocument );\n\n  postMethod.setRequestEntity( new StringRequestEntity( smsRequestDocument ) );\n  LOG.debug( \"commiting SMS to aggregator: \" + textMessage.toString() );\n  int httpStatus = httpClient.executeMethod( postMethod );\n"], "symptom_rank": 6, "environment_rank": 1, "exception_stack_rank": 10, "exception_message": "    java.net.SocketException: Connection reset\n", "symptom_score": 82, "environment_score": 97, "exception_stack_score": 70}, {"answer_id": "16191236", "title": "Tomcat startup fails due to 'java.net.SocketException Invalid argument' on Mac OS X", "Score": 29, "ViewCount": 14359, "LastEditDate": "2017-05-23 11:51:35", "LastActivityDate": "2014-11-25 14:28:20", "AnswerScore": 21, "reason": ["Interestingly the Oracle documentation uses a PlainSocketImpl.socketAccept error as an example of when to use this. ", "Note also that the implication of Bug 7131399 is that the JNI uses poll(. on most platforms but select(on Mac OS due to a problem with poll(on the Mac", "So maybe select(. is broken too", "Digging in a bit further, select(. will return EINVAL if \"ndfs is greater than FD_SETSIZE and _DARWIN_UNLIMITED_SELECT is not defined.", "FD_SETSIZE is 1024 and it sounds like you have a ton of applications loading up, so perhaps it all filters down to waiting on more that 1024 FDs at one time. ", "Java bug is in fact fixed on your machine. ", "FD_SETSIZE limitation is the cause. "], "solution": [], "answer_code": ["import java.io.*;\nimport java.net.*;\n\npublic class SelectTest {\n  public static void main(String[] args) throws Exception {\n    // Use 1024 file descriptors. There'll already be some in use, obviously, but this guarantees the problem will occur\n    for(int i = 0; i < 1024; i++) {\n      new FileInputStream(\"/dev/null\");\n    }\n    ServerSocket socket = new ServerSocket(8080);\n    socket.accept();\n  }\n}\n"], "environment": ["socketexception (they're outgoing http calls to web services)", "file descriptor limits . increased from 5000 to 10000", "mac os 10.7.x and 10.8.0", "jdk7u", "localhost", "jdk regression", "java-native-interface", "mac os w/ java 1.7", "fusion", "accept system", "tomcat 6", "jni code", "openjdk sources", "ipv6", "socketaccept", "libraries", "application", "arg0", "mac os", "socketexceptions", "tomcat", "tomcat startup", "java"], "symptom": ["We have an application that runs on Tomcat 6 (6.0.35.0 to be precise), and most of our engineers on Mac OS are having problems starting Tomcat due to the socketAccept call in the Catalina.await method throwing a SocketException: -CODE-. ", "This causes Tomcat to shut down immediately after startup (and no small amount of rage). ", "We think this has been with us for the duration on Mac OS w/ Java 1.7, in the last several months a lot of us have switched to Macbook Pros. ", "Up until now, the only symptom was occasional zero byte responses from Tomcat, due to this exception also being thrown on a socketRead. ", "Errors don't hit the logs and we'd individually shrugged it off as an isolated problem, and only found the cause when the startup problem started and I set a SocketException breakpoint: -CODE-. ", "Increasing startup time due to application changes (lots more Spring introspection/singleton overhead. seems to be the factor that causes this to affect Tomcat startup; the tipping point being about 160 seconds", "We can mitigate the problem by disabling some of the non-mandatory contexts we don't need during development to reduce startup time, but I'd prefer to find the root cause. ", "Application configuration The specifics of the application are far too complex to go into too much detail, but I have a hunch that this might relate to an earlier bind, so I'll at least list the listening ports on my machine: -CODE-. ", "Items ruled out [-]The most obvious solution: -Djava.net.preferIPv4Stack=true. ", "I've always had that option configured. ", "[-]Any recent configuration change to our base application configuration, libraries, JVM options (there aren't any. ", "[-]A JDK regression. ", "I've tested JDK 1.7.0_09, 11, 15, 17 and 21 (the JDKs I've had installed on my machine for the duration. ", "Mac OS 10.7.x and 10.8.0 through 1.8.3 are affected. ", "[-]File descriptor limits . increased from 5000 to 10000", "[-]Disabling IPv6 completely on the main ethernet interface. ", "[-]Setting breakpoints, and removing the first contexts to be affected by the SocketException (they're outgoing HTTP calls to web services). ", "[-]Configuring /etc/hosts so the machine hostname resolves to localhost, and configuring JVM options to prefer IPv4 and to not prefer IPv6 addresses (This answer: https://stackoverflow.com/a/16318860/364206. ", "For those interested in hosts configuration, it's the same as default. ", "I can reproduce this on a Fusion VM w/ a clean install of 10.8: -CODE-. ", "Java code investigation Due to the apparent time sensitive nature of the issue, setting breakpoints to troubleshoot the issue causes it to not occur. ", "As requested in the comments, I also captured arg0 for SocksSocketImpl(PlainSocketImpl).socketAccept(SocketImpl), nothing seems out of the ordinary. -CODE-", "I think all of the threads where the exceptions are thrown are victims of an earlier call, one that doesn't result in a SocketException so I haven't been able to catch it. ", "Being able to start Tomcat by reducing startup times convinces me that the trigger is probably some scheduled task that performs a socket based operation, which then affects other socket operations. ", "That doesn't explain how and why this could affect several threads, no matter what we're doing to cause this condition, mysterious SocketExceptions shouldn't bubble up from native code and cause these exceptions simultaneously on multiple threads . that is, two threads making outgoing web service calls, the Tomcat await call, and several TP processor threads repeatedly", "JNI code investigation Given the generic message, I assumed that an EINVAL error must be returned from one of the system calls in the socketAccept JNI code, so I traced the system calls leading up to the exception; there's no EINVAL returned from any system call. ", "So, I went to the OpenJDK sources looking for conditions in the socketAccept code that would set and then throw an EINVAL, but I also couldn't find any code that sets errno to EINVAL, or calls NET_ThrowByNameWithLastError, NET_ThrowCurrent or NET_ThrowNew in a way that would throw a SocketException with this default error message. ", "As far as the system calls, we don't seem to get as far as the accept system call: -CODE-. ", "So, I think the problem occurs in the timeout handling code at the top of the accept loop in socketAccept, but I couldn't find any case where NET_Timeout would set errno to EINVAL, and result in this SocketException being thrown. ", "I'm referring to this code; I assume the jdk7u branch is for the most part what ships in the Oracle JDK: [-]http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/file/d4bf5c15837c/src/solaris/native/java/net/PlainSocketImpl.c. ", "[-]http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/file/d4bf5c15837c/src/solaris/native/java/net/bsd_close.c. ", "[-]http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/file/d4bf5c15837c/src/solaris/native/java/net/net_util_md.c. ", "I can't find anyone in the outside world affected by this particular problem on Mac OS, but almost everyone here is affected. ", "There must be some application configuration that contributes, but I've exhausted every avenue I can think of to find the root cause. "], "exception_stack": ["SEVERE: StandardServer.await: accept:\njava.net.SocketException: Invalid argument\n      at java.net.PlainSocketImpl.socketAccept(Native Method)\n      at java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java)\n      at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)\n      at java.net.ServerSocket.implAccept(ServerSocket.java:522)\n      at java.net.ServerSocket.accept(ServerSocket.java:490)\n      at org.apache.catalina.core.StandardServer.await(StandardServer.java:431)\n      at org.apache.catalina.startup.Catalina.await(Catalina.java:676)\n      at org.apache.catalina.startup.Catalina.start(Catalina.java:628)\n      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n      at java.lang.reflect.Method.invoke(Method.java:601)\n      at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)\n      at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)\n      at mycompany.tomcat.startup.ThreadDumpWrapper.main(ThreadDumpWrapper.java:260)\n      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n      at java.lang.reflect.Method.invoke(Method.java:601)\n      at org.tanukisoftware.wrapper.WrapperStartStopApp.run(WrapperStartStopApp.java:238)\n      at java.lang.Thread.run(Thread.java:722)\n", " PID/THRD        RELATIVE   ELAPSD    CPU SYSCALL(args)    = return\n 6606/0x2c750d:  221538243       5      0 sigprocmask(0x1, 0x0, 0x14D8BE100)    = 0x0 0\n 6606/0x2c750d:  221538244       3      0 sigaltstack(0x0, 0x14D8BE0F0, 0x0)     = 0 0\n 6606/0x2c750d:  221538836      14     10 socket(0x2, 0x1, 0x0)    = 1170 0\n 6606/0x2c750d:  221538837       3      0 fcntl(0x492, 0x3, 0x4)     = 2 0\n 6606/0x2c750d:  221538839       3      1 fcntl(0x492, 0x4, 0x6)     = 0 0\n 6606/0x2c750d:  221538842       5      2 setsockopt(0x492, 0xFFFF, 0x4)     = 0 0\n 6606/0x2c750d:  221538852       7      4 bind(0x492, 0x14D8BE5D8, 0x10)     = 0 0\n 6606/0x2c750d:  221538857       5      2 listen(0x492, 0x1, 0x4)    = 0 0\n 6606/0x2c750d:  221539625       6      2 psynch_cvsignal(0x7FEFBFE00868, 0x10000000200, 0x100)    = 257 0\n 6606/0x2c750d:  221539633       4      1 write(0x2, \"Apr 18, 2013 11:05:35 AM org.apache.catalina.core.StandardServer await\\nSEVERE: StandardServer.await: accept: \\njava.net.SocketException: Invalid argument\\n\\tat java.net.PlainSocketImpl.socketAccept(Native Method)\\n\\tat java.net.PlainSocketImpl.socketAcce\", 0x644)    = 1604 0\n"], "code": ["Daemon Thread [http-8080-1] (Suspended (breakpoint at line 47 in SocketException))  \n  SocketException.<init>(String) line: 47 \n  SocketInputStream.socketRead0(FileDescriptor, byte[], int, int, int) line: not available [native method] \n  SocketInputStream.socketRead0(FileDescriptor, byte[], int, int, int) line: not available  \n  SocketInputStream.read(byte[], int, int, int) line: 150 \n  SocketInputStream.read(byte[], int, int) line: 121  \n  InternalInputBuffer.fill() line: 735  \n  InternalInputBuffer.parseRequestLine() line: 366  \n  Http11Processor.process(Socket) line: 814 \n  Http11Protocol$Http11ConnectionHandler.process(Socket) line: 602  \n  JIoEndpoint$Worker.run() line: 489  \n  Thread.run() line: 722  \n", "arg0  FileDescriptor  (id=499)  \n  fd  1097  \n  useCount  AtomicInteger  (id=503) \n    value 2 \narg1  (id=502)\narg2  0 \narg3  8192  \narg4  20000 \n", "localhost:32000 - Java service wrapper port\n*:10001         - RMI registry\n*:2322          - Java debug\n*:56566         - RMI\n*:8180          - Tomcat HTTP connector\n*:8543          - Tomcat HTTPS connector\n*:2223          - Tomcat Internal HTTP connector (used for cross-server requests)\n*:14131         - 'Locking' port to determine if an internal service is running\n*:56571         - EhCache RMI\n*:56573         - RMI\n*:62616         - ActiveMQ broker\n*:5001          - SOAPMonitorService\n*:8109          - Tomcat shutdown port\n", "##\n# Host Database\n#\n# localhost is used to configure the loopback interface\n# when the system is booting.  Do not change this entry.\n##\n127.0.0.1   localhost\n255.255.255.255 broadcasthost\n::1             localhost\nfe80::1%lo0 localhost\n", "arg0  SocksSocketImpl  (id=460) \n  address InetAddress  (id=465) \n    canonicalHostName null  \n    holder  InetAddress$InetAddressHolder  (id=475) \n      address 0 \n      family  0 \n      hostName  null  \n  applicationSetProxy false \n  closePending  false \n  cmdIn null  \n  cmdOut  null  \n  cmdsock null  \n  CONNECTION_NOT_RESET  0 \n  CONNECTION_RESET  2 \n  CONNECTION_RESET_PENDING  1 \n  external_address  null  \n  fd  FileDescriptor  (id=713)  \n    fd  -1  \n    useCount  AtomicInteger  (id=771) \n      value 0 \n  fdLock  Object  (id=714)  \n  fdUseCount  0 \n  localport 0 \n  port  0 \n  resetLock Object  (id=716)  \n  resetState  0 \n  server  null  \n  serverPort  1080  \n  serverSocket  null  \n  shut_rd false \n  shut_wr false \n  socket  Socket  (id=718)  \n    bound false \n    closed  false \n    closeLock Object  (id=848)  \n    connected false \n    created false \n    impl  null  \n    oldImpl false \n    shutIn  false \n    shutOut false \n  socketInputStream null  \n  stream  false \n  timeout 0 \n  trafficClass  0 \n  useV4 false \n"], "purpose": ["We have an application that runs on Tomcat 6 (6.0.35.0 to be precise), and most of our engineers on Mac OS are having problems starting Tomcat due to the socketAccept call in the Catalina.await method throwing a SocketException: -CODE-. "], "purpose_rank": 10, "symptom_rank": 11, "environment_rank": 18, "exception_message": "java.net.SocketException: Invalid argument\n", "purpose_score": 70, "symptom_score": 67, "environment_score": 46}, {"answer_id": "20207276", "title": "Jersey on Tomcat 7 throws java.net.SocketException: Invalid argument", "Score": 0, "ViewCount": 496, "LastEditDate": "", "LastActivityDate": "2013-12-03 00:30:50", "AnswerScore": 0, "reason": [], "solution": ["Running the apps on separate Virtual Machines fixed the problem."], "answer_code": [], "environment": ["jersey", "tomcat 7", "tomcat7", "exception", "python", "java 1.7.0_25", "socketexception", "java"], "symptom": ["I've built two Jersey web applications and running both of them on Tomcat 7. ", "For the sake of simplicity I'll call them \"App A. and \"App B\"", "There is an endpoint on \"App A. that internally makes an HTTP request to \"App B\"", "When consuming this endpoint on \"App A. in Java, it occasionally returns the following exception when trying to make the request to \"App B\": -CODE-", "The exception happens exactly where \"App A. tries to make a request to \"App B\"", "This happens with Tomcat 7 running in Eclipse, and also when it runs standalone. ", "And it happens with both MacOSX 10.9 and Centos 6. ", "Trying to make the same request with Python, it ocassionally returns the same exception: -CODE-. ", "I'm running Java 1.7.0_25, Jersey 2.4.1, Tomcat 7, and MacOSX 10.9 (or Centos 6). "], "exception_stack": ["java.net.SocketException: Invalid argument\n    at java.net.SocketInputStream.socketRead0(Native Method)\n    at java.net.SocketInputStream.read(SocketInputStream.java:150)\n    at java.net.SocketInputStream.read(SocketInputStream.java:121)\n    at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:67)\n    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:130)\n    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:146)\n    at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:259)\n    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)\n    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:58)\n    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:262)\n    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)\n    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n    at java.lang.reflect.Method.invoke(Method.java:606)\n    at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)\n    at com.sun.proxy.$Proxy141.receiveResponseHeader(Unknown Source)\n    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)\n    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)\n    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)\n    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:176)\n    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:77)\n    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:101)\n    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)\n    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)\n    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)\n    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)\n", "  File \"/Library/Python/2.7/site-packages/requests/api.py\", line 88, in post\n    return request('post', url, data=data, **kwargs)\n  File \"/Library/Python/2.7/site-packages/requests/api.py\", line 44, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/Library/Python/2.7/site-packages/requests/sessions.py\", line 361, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/Library/Python/2.7/site-packages/requests/sessions.py\", line 464, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Library/Python/2.7/site-packages/requests/adapters.py\", line 356, in send\n    raise ConnectionError(e)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /mashape-apis-database-server/v1/tags/ (Caused by <class 'httplib.BadStatusLine'>: '')\n"], "code": [], "environment_rank": 3, "exception_message": "java.net.SocketException: Invalid argument\n", "environment_score": 91}, {"answer_id": "50574949", "title": "java.net.SocketException: Connection reset - Between a client and server deployed as webapps in tomcat", "Score": 0, "ViewCount": 967, "LastEditDate": "", "LastActivityDate": "2019-01-03 18:37:38", "AnswerScore": 1, "reason": ["After performance testing was done on our application , the result showed that after multiple concurrent requests the application was stalling to create HttpClient objects."], "solution": ["I ended up using \"ClientConnectionPoolManager\".(Maintains a pool of HttpClientConnections and is able to service connection requests from multiple execution threads. ", "Connections are pooled on a per route basis. ", "A request for a route which already the manager has persistent connections for available in the pool will be services by leasing a connection from the pool rather than creating a brand new connection. and this seems to manage the connections effectively"], "answer_code": [], "environment": ["client server", "server 1 and server 2 which are client facing load balanced servers", "connection-timeout", "core systems", "tomcat", "freeze", "java", "server 3 and 4", "sockets"], "symptom": ["I have a java gateway application deployed as tomcat web application on server 1 and server 2 which are client facing load balanced servers. ", "This app communicates with another webapp deployed on server 3 and 4 which are also load balanced. ", "During high volume times or when there is a connection failure to backend core systems from app(server 3 and 4. , the gateway app is logging 'java.net.SocketException: Connection reset'", "For 10 requests, couple of requests gives 'Connection reset' on the client server.When this is happening there are absolutely no issues on the server side application.Sometime when there is more failures the app(Server 3 and 4. hangs and needs to be restarted"], "exception_stack": [], "code": [], "purpose": ["I have a java gateway application deployed as tomcat web application on server 1 and server 2 which are client facing load balanced servers. "], "purpose_rank": 0, "exception_message": "", "purpose_score": 100}, {"answer_id": "27206128", "title": "Java PHP FastCGI SocketException: Connection Reset on reading data", "Score": 1, "ViewCount": 332, "LastEditDate": "2014-11-29 20:11:32", "LastActivityDate": "2014-12-01 06:06:40", "AnswerScore": 2, "reason": [], "solution": ["I found out what it was, I was sending content without a content length and it didn't like that."], "answer_code": [], "environment": ["java", "fastcgi", "php-cgi", "java 8", "java webserver", "fastcgi client", "php"], "symptom": ["I'm trying to write a php-cgi connection for the Java webserver I'm developing but it's not really working. ", "I'm currently trying to write a fastcgi client using this php client as an example https://github.com/adoy/PHP-FastCGI-Client/blob/master/src/Adoy/FastCGI/Client.php. ", "I somehow managed to get php-cgi to parse php files from my request. ", "However, only about 1 in 4 requests sorta kinda succeeds and then fails when I'm trying to read more data: -CODE-. ", "The rest of them just flunks: -CODE-. ", "I'm currently running php-cgi from commandprompt with php-cgi -b 127.0.0.1:8091 And I'm using this code to test: -CODE-. ", "I'm using Java 8 and an unedited PHP 5.6.1 from windows.php.net. "], "exception_stack": ["java.net.SocketException: Connection reset\n    at java.net.SocketInputStream.read(Unknown Source)\n    at java.net.SocketInputStream.read(Unknown Source)\n    at java.net.SocketInputStream.read(Unknown Source)\n    at com.bit_stab.fastcgi.client.Packet.<init>(Packet.java:26)\n    at com.bit_stab.fastcgi.client.Client.readResponse(Client.java:51)\n    at com.bit_stab.webdragonplugin.php.PHPPlugin.runPhpCgi(PHPPlugin.java:98)\n    at com.bit_stab.webdragonplugin.php.PHPPlugin.main(PHPPlugin.java:42)\n", "java.net.SocketException: Connection reset\n    at java.net.SocketInputStream.read(Unknown Source)\n    at java.net.SocketInputStream.read(Unknown Source)\n    at java.net.SocketInputStream.read(Unknown Source)\n    at com.bit_stab.fastcgi.client.Packet.<init>(Packet.java:37)\n    at com.bit_stab.fastcgi.client.Client.readResponse(Client.java:46)\n    at com.bit_stab.webdragonplugin.php.PHPPlugin.runPhpCgi(PHPPlugin.java:98)\n    at com.bit_stab.webdragonplugin.php.PHPPlugin.main(PHPPlugin.java:42)\n"], "code": ["public static void main(String[] args)\n{\n    try\n    {\n        HashMap<String, String> map = new HashMap<String, String>();\n\n        map.put( \"DOCUMENT_ROOT\" , \"D:/Programma's/Eclipse/Workspaces/Java/HTTPWebServer/test root\" );\n        map.put( \"SCRIPT_FILENAME\" , \"D:/Programma's/Eclipse/Workspaces/Java/HTTPWebServer/test root/index.php\" );\n        map.put( \"SCRIPT_NAME\" , \"/index.php\" );\n        map.put( \"DOCUMENT_URI\" , \"/index.php\" );\n        map.put( \"REQUEST_METHOD\" , \"GET\" );\n        map.put( \"SERVER_PROTOCOL\" , \"HTTP/1.1\" );\n        map.put( \"REDIRECT_STATUS\" , \"200\" );\n        map.put( \"PHP_SELF\" , \"/index.php\" );\n        map.put( \"HOME\" , \"D:/Programma's/Eclipse/Workspaces/Java/HTTPWebServer/test root\" );\n        map.put( \"FCGI_ROLE\" , \"RESPONDER\" );\n        map.put( \"HTTP_CONNECTION\" , \"keep-alive\" );\n\n\n        Client c = new Client( \"127.0.0.1\" , 8090 );\n        c.asyncRequest( map , \"GET /index.php HTTP/1.1\\r\\nConnection: Keep-Alive\\r\\n\\r\\n\" );\n        c.readResponse();\n    }\n    catch( Exception e )\n    {\n        // TODO Auto-generated catch block\n        e.printStackTrace();\n    }\n}\n", "package com.bit_stab.fastcgi.client;\n\nimport java.io.ByteArrayOutputStream;\nimport java.io.IOException;\nimport java.io.InputStream;\nimport java.io.OutputStream;\nimport java.net.Socket;\nimport java.net.UnknownHostException;\nimport java.util.Map;\nimport java.util.Map.Entry;\n\npublic class Client\n{\n    private Socket socket;\n    private short reqId = 0b0; //TODO singleton requestID counter\n\n    public Client( String host, int port ) throws UnknownHostException, IOException\n    {\n        socket = new Socket( host, port );\n    }\n\n    public short asyncRequest( Map<String, String> params, String content ) throws IOException\n    {\n        ByteArrayOutputStream paramBytes = new ByteArrayOutputStream();\n\n        for ( Entry<String, String> param: params.entrySet() )\n            paramBytes.write( nvpair( param.getKey() , param.getValue() ) );\n\n        Packet beginRequest = new Packet( (byte) 1, reqId, new byte[] { 0, 1, 1, 0, 0, 0, 0, 0 } );\n        Packet requestParams = new Packet( (byte) 4, reqId, paramBytes.toByteArray() );\n        Packet requestContent = new Packet( (byte) 5, reqId, content.getBytes() );\n\n        OutputStream stream = socket.getOutputStream();\n\n        stream.write( beginRequest.getBytes() );\n        stream.write( requestParams.getBytes() );\n        stream.write( requestContent.getBytes() );\n\n        return reqId++;\n    }\n\n    public void readResponse() throws IOException\n    {\n        InputStream stream = socket.getInputStream();\n\n        Packet response = new Packet( stream );\n\n        System.out.println( new String( response.getContent() ) );\n\n        Packet p;\n        while ( ( p = new Packet( stream ) ).getType() != 3 )\n            System.out.println( new String( p.getContent() ) );\n    }\n\n    public byte[] nvpair( String name, String value )\n    {\n        try\n        {\n            int nl = name.length();\n            int vl = value.length();\n\n            ByteArrayOutputStream bytes = new ByteArrayOutputStream( nl + vl + 10 );\n\n            if ( nl < 256 )\n                bytes.write( (byte) nl );\n            else\n                bytes.write( new byte[] { b( nl >> 24 ), b( nl >> 16 ), b( nl >> 8 ), b( nl ) } );\n\n            if ( vl < 256 )\n                bytes.write( (byte) vl );\n            else\n                bytes.write( new byte[] { b( vl >> 24 ), b( vl >> 16 ), b( vl >> 8 ), b( vl ) } );\n\n            bytes.write( name.getBytes( \"UTF-8\" ) );\n            bytes.write( value.getBytes( \"UTF-8\" ) );\n\n            return bytes.toByteArray();\n        }\n        catch( IOException e )\n        {\n            e.printStackTrace();\n        }\n        return null;\n    }\n\n    public byte b( int i )\n    {\n        return (byte) i;\n    }\n}\n", "package com.bit_stab.fastcgi.client;\n\nimport java.io.IOException;\nimport java.io.InputStream;\n\npublic class Packet\n{\n    private byte version = 1;\n    private byte type;\n    private short requestId;\n    private byte paddingLength = 0;\n    private byte reserved = 0;\n\n    private byte[] content;\n\n    public Packet( byte type, short requestId, byte... content )\n    {\n        this.type = type;\n        this.requestId = requestId;\n        this.content = content;\n    }\n\n    public Packet( InputStream stream ) throws IOException\n    {\n        byte[] head = new byte[8];\n        stream.read( head );\n\n        this.version = head[0];\n        this.type = head[1];\n        this.requestId = (short)( ( ( head[2] & 0xFF ) << 8 ) | ( head[3] & 0xFF ) );\n        int contentLength =     ( ( ( head[4] & 0xFF ) << 8 ) | ( head[5] & 0xFF ) );\n        this.paddingLength = head[6];\n        this.reserved = head[7];\n\n        this.content = new byte[contentLength];\n\n        stream.read( content );\n        stream.skip( paddingLength & 0xFF );\n    }\n\n    public byte getType()\n    {\n        return type;\n    }\n\n    public short getId()\n    {\n        return requestId;\n    }\n\n    public byte[] getContent()\n    {\n        return content;\n    }\n\n    public byte[] getBytes()\n    {\n        byte[] b = new byte[8 + content.length];\n\n        b[0] = version;\n        b[1] = type;\n        b[2] = (byte) ( requestId >> 8 );\n        b[3] = (byte) requestId;\n        b[4] = (byte) ( content.length >> 8 );\n        b[5] = (byte) content.length;\n        b[6] = paddingLength;\n        b[7] = reserved;\n\n        for ( int i = 0; i < content.length; i++ )\n            b[i + 8] = content[i];\n\n        return b;\n    }\n}\n"], "exception_message_rank": 0, "title_rank": 6, "exception_message": "java.net.SocketException: Connection reset\n", "exception_message_score": 100}, {"answer_id": "36979706", "title": "setting 'Content-Encoding' to gzip or deflate causes java.net.SocketException: Connection reset", "Score": 1, "ViewCount": 7328, "LastEditDate": "2020-06-20 09:12:55", "LastActivityDate": "2018-07-31 06:24:47", "AnswerScore": 2, "reason": [], "solution": ["I removed this wrong statement: response.setHeader(\"Content-Encoding\",\"gzip\"); And I have added my servlet url to the GZIP Filter url pattern. "], "answer_code": ["HTTP/1.1 200 OK\nServer: Apache-Coyote/1.1\nContent-Encoding: gzip\nAccept-Ranges: bytes\nVary: Accept-Encoding\nAccess-Control-Allow-Origin: *\nContent-Disposition: attachment; filename=1.2.410.200028.456.20151027.10647.1.1.dcm\nContent-Type: application/dicom\nTransfer-Encoding: chunked\n"], "environment": ["java servlet", "jdk1.8.0_77", "servlet", "gzip", "servlets", "content-encoding", "java", "tomcat"], "symptom": ["I have developed a simple Java Servlet in order to retrieve a medical file(DICOM. from a server: -CODE-", "If I comment this line: -CODE-. the servlet works fine, but adding the above line would cause: -CODE-for some reasons I want to simulate an other server behavior which has below HTTP Response Header: -CODE-", "I am using 'jdk1.8.0_77' and 'apache-tomcat-7.0.62'. "], "exception_stack": ["org.apache.catalina.connector.ClientAbortException: java.net.SocketException: Connection reset\nat org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:367)\nat org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:331)\nat org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:101)\nat pages.DicomRetrieveServlet.doGet(DicomRetrieveServlet.java:107)\nat javax.servlet.http.HttpServlet.service(HttpServlet.java:624)\nat javax.servlet.http.HttpServlet.service(HttpServlet.java:731)\nat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)\nat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\nat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\nat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\nat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\nat org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:438)\nat org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:179)\nat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\nat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\nat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)\nat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)\nat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)\nat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)\nat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)\nat org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)\nat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)\nat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)\nat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)\nat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)\nat org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)\nat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\nat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\nat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\nat java.lang.Thread.run(Thread.java:745)\nCaused by: java.net.SocketException: Connection reset\nat java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)\nat java.net.SocketOutputStream.write(SocketOutputStream.java:153)\nat org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:215)\nat org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:480)\nat org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:119)\nat org.apache.coyote.http11.AbstractHttp11Processor.action(AbstractHttp11Processor.java:801)\nat org.apache.coyote.Response.action(Response.java:172)\nat org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:363)\n... 29 more\n"], "code": ["public class DicomRetrieveServlet extends HttpServlet {\n\nprivate static Logger log = Logger.getLogger(DicomRetrieveServlet.class);\n\npublic void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {\n    String dicomFilepath = \"PATH TO MY FILE\";\n\n    InputStream resultInStream = null;\n    response.setHeader(\"Accept-Ranges\",\"bytes\");\n    response.setHeader(\"Vary\", \"Accept-Encoding\");\n    response.setHeader(\"Content-Encoding\", \"gzip\");\n    response.setHeader(\"Access-Control-Allow-Origin\",\"*\");\n    response.setContentType(\"application/dicom\");\n\n    try (OutputStream out = response.getOutputStream()) {\n        int bytes_read;\n        resultInStream = new FileInputStream(dicomFilepath.toString());\n        byte[] buffer = new byte[4096];\n        while ((bytes_read = resultInStream.read(buffer)) != -1) {\n            out.write(buffer, 0, bytes_read);\n        }\n        out.flush();\n    } catch (Exception e) {\n        log.error(\"Error while streaming DICOM image \", e);\n    }\n}\n", "        response.setHeader(\"Content-Encoding\", \"gzip\");\n", "HTTP/1.1 200 OK\nDate: Fri, 29 Apr 2016 14:13:51 GMT\nServer: Apache/2.2.15 (CentOS)\nLast-Modified: Mon, 07 Apr 2014 18:40:46 GMT\nETag: \"14034f-8257c-4f67834a723b4\"\nAccept-Ranges: bytes\nVary: Accept-Encoding\nContent-Encoding: gzip\nAccess-Control-Allow-Origin: *\nContent-Type: application/dicom\n", "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36\nX-DevTools-Emulate-Network-Conditions-Client-Id: 922810C0-22E8-4F8A-8E15-894B36DAB06A\nAccept: '*/*'\nReferer: http://localhost:8080/myapp/viewImageCornerStone.jsf?studyUID=1.2.410.200028.456.20151027.10647\nAccept-Encoding: gzip, deflate, sdch\nAccept-Language: en-US,en;q=0.8,fa;q=0.6\nCookie: JSESSIONID=FABFF5F057EE4786E2920E5DFA47376C\n"], "environment_rank": 28, "exception_message_rank": 8, "exception_stack_rank": 2, "exception_message": "org.apache.catalina.connector.ClientAbortException: java.net.SocketException: Connection reset\nCaused by: java.net.SocketException: Connection reset\n", "environment_score": 16, "exception_message_score": 76, "exception_stack_score": 94}, {"answer_id": "9159372", "title": "java.net.SocketException: Broken pipe with Quartz and MySQL and Tomcat (Tomcat Crash)", "Score": 3, "ViewCount": 4786, "LastEditDate": "2012-02-06 13:39:36", "LastActivityDate": "2012-02-06 13:39:36", "AnswerScore": 4, "reason": ["I believe it is related to MySQL stale connection that is dropped after 8 hours. "], "solution": ["Make sure you have the following set (not sure about the exact attributes' names but they should be similar to the mentioned below)", "testWhileIdle=true\nvalidationQuery=\"SELECT 1\"\nminEvictableIdleTimeMillis=1800000\ntimeBetweenEvictionRunsMillis=1800000\nnumTestsPerEvictionRun=3\n"], "answer_code": [], "environment": ["java", "quartz-scheduler", "server", "my local machine", "tomact crash", "socketexception", "job-scheduling", "quartz properties", "quartz jar 1.6.5 and tomcat 6.0.18", "mysql"], "symptom": ["Following is the stack trace. ", "I read that the Broken Pipe is because of Unclosed connection for 8 hours and the connection close automatically. ", "I saw this http://itellity.wordpress.com/2011/05/18/getting-rid-of-socketexception-broken-pipe-with-quartz-and-mysql-on-jboss/ .I could not reproduce in my local machine. ", "[-]Is there any way I can reproduce this in my local machine. ", "[-]Will this make a tomact crash. ", "I am using a very old version of quartz jar 1.6.5 and tomcat 6.0.18. will that be an issue", "EDIT: I am using: -CODE-. on my quartz properties also: -CODE-", "Is there any way I can reproduce this by changing the mysql properties. ", "I am getting this only on my server. "], "exception_stack": ["[Scheduler_QuartzSchedulerThread] WARN org.quartz.impl.jdbcjobstore.JobStoreTX - Failed to override connection auto commit/transaction isolation.\ncom.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: \n\n** BEGIN NESTED EXCEPTION ** \n\njava.net.SocketException\nMESSAGE: Broken pipe\n\nSTACKTRACE:\n\njava.net.SocketException: Broken pipe\n    at java.net.SocketOutputStream.socketWrite0(Native Method)\n    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)\n    at java.net.SocketOutputStream.write(SocketOutputStream.java:136)\n    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)\n    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)\n    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:2744)\n    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1612)\n    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)\n    at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)\n    at com.mysql.jdbc.Connection.setAutoCommit(Connection.java:5442)\n    at org.apache.commons.dbcp.DelegatingConnection.setAutoCommit(DelegatingConnection.java:237)\n    at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.setAutoCommit(AttributeRestoringConnectionInvocationHandler.java:91)\n    at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:65)\n    at $Proxy4.setAutoCommit(Unknown Source)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:711)\n    at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:72)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3757)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2729)\n    at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:266)\n\n\n** END NESTED EXCEPTION **\n\n\n\nLast packet sent to the server was 1 ms ago.\n    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:2759)\n    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1612)\n    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)\n    at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)\n    at com.mysql.jdbc.Connection.setAutoCommit(Connection.java:5442)\n    at org.apache.commons.dbcp.DelegatingConnection.setAutoCommit(DelegatingConnection.java:237)\n    at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.setAutoCommit(AttributeRestoringConnectionInvocationHandler.java:91)\n    at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:65)\n    at $Proxy4.setAutoCommit(Unknown Source)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:711)\n    at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:72)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3757)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2729)\n    at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:266)\n[Scheduler_QuartzSchedulerThread] WARN org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler - Failed restore connection's original auto commit setting.\ncom.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: \n\n** BEGIN NESTED EXCEPTION ** \n\njava.net.SocketException\nMESSAGE: Broken pipe\n\nSTACKTRACE:\n\njava.net.SocketException: Broken pipe\n    at java.net.SocketOutputStream.socketWrite0(Native Method)\n    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)\n    at java.net.SocketOutputStream.write(SocketOutputStream.java:136)\n    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)\n    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)\n    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:2744)\n    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1612)\n    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)\n    at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)\n    at com.mysql.jdbc.Connection.setAutoCommit(Connection.java:5442)\n    at org.apache.commons.dbcp.DelegatingConnection.setAutoCommit(DelegatingConnection.java:237)\n    at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.restoreOriginalAtributes(AttributeRestoringConnectionInvocationHandler.java:134)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.cleanupConnection(JobStoreSupport.java:3551)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3774)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2729)\n    at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:266)\n\n\n** END NESTED EXCEPTION **\n\n\n\nLast packet sent to the server was 0 ms ago.\n    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:2759)\n    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1612)\n    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)\n    at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)\n    at com.mysql.jdbc.Connection.setAutoCommit(Connection.java:5442)\n    at org.apache.commons.dbcp.DelegatingConnection.setAutoCommit(DelegatingConnection.java:237)\n    at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.restoreOriginalAtributes(AttributeRestoringConnectionInvocationHandler.java:134)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.cleanupConnection(JobStoreSupport.java:3551)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3774)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2729)\n    at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:266)\n[Scheduler_QuartzSchedulerThread] ERROR org.quartz.core.ErrorLogger - An error occured while scanning for the next trigger to fire.\norg.quartz.JobPersistenceException: Couldn't acquire next trigger: Communications link failure due to underlying exception: \n\n** BEGIN NESTED EXCEPTION ** \n\njava.net.SocketException\nMESSAGE: Broken pipe\n\nSTACKTRACE:\n\njava.net.SocketException: Broken pipe\n    at java.net.SocketOutputStream.socketWrite0(Native Method)\n    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)\n    at java.net.SocketOutputStream.write(SocketOutputStream.java:136)\n    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)\n    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)\n    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:2744)\n    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1612)\n    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)\n    at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)\n    at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)\n    at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1447)\n    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:177)\n    at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTriggerToAcquire(StdJDBCDelegate.java:2924)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2747)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport$36.execute(JobStoreSupport.java:2733)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3760)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2729)\n    at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:266)\n\n\n** END NESTED EXCEPTION **\n\n\n\nLast packet sent to the server was 1 ms ago. [See nested exception: com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: \n\n** BEGIN NESTED EXCEPTION ** \n\njava.net.SocketException\nMESSAGE: Broken pipe\n\nSTACKTRACE:\n\njava.net.SocketException: Broken pipe\n    at java.net.SocketOutputStream.socketWrite0(Native Method)\n    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)\n    at java.net.SocketOutputStream.write(SocketOutputStream.java:136)\n    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)\n    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)\n    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:2744)\n    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1612)\n    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)\n    at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)\n    at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)\n    at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1447)\n    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:177)\n    at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTriggerToAcquire(StdJDBCDelegate.java:2924)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2747)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport$36.execute(JobStoreSupport.java:2733)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3760)\n    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2729)\n    at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:266)\n\n\n** END NESTED EXCEPTION **\n"], "code": ["org.quartz.dataSource.QUARTZ_NO_TX.validateOnCheckout = true\norg.quartz.dataSource.QUARTZ_NO_TX.validationQuery = select 1\n", "autoreconnect=true\n"], "environment_rank": 15, "title_rank": 7, "exception_message": "com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: \njava.net.SocketException\njava.net.SocketException: Broken pipe\ncom.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: \njava.net.SocketException\njava.net.SocketException: Broken pipe\norg.quartz.JobPersistenceException: Couldn't acquire next trigger: Communications link failure due to underlying exception: \njava.net.SocketException\njava.net.SocketException: Broken pipe\nLast packet sent to the server was 1 ms ago. [See nested exception: com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: \njava.net.SocketException\njava.net.SocketException: Broken pipe\n", "environment_score": 55}, {"answer_id": "18947088", "title": "SocketException: Connection reset on server with ObjectInputStream", "Score": 1, "ViewCount": 13088, "LastEditDate": "2013-09-22 18:37:11", "LastActivityDate": "2015-04-19 20:06:12", "AnswerScore": 1, "reason": ["You're reading the object twice, but only printing the second time. ", "So the client is probably shutdown by the time you try to read the second time, and so the socket has been closed on the remote end, hence exception. ", "You're reading in an object on the != null check. ", "It's a stream, not a buffer. "], "solution": ["You don't print it. ", "Then you try to read it again and it bombs. ", "You might want to buffer the read, and then you can inspect that buffer as much as you like. ", "Simplest example... -CODE-"], "answer_code": ["Object o = outputStream.readObject();\nif(o != null) {\n system.out.println(o);\n}\n"], "environment": ["edit", "hashmap", "server", "sockets", "objectoutputstream", "java", "objectinputstream/objectoutputstream", "objectinputstream", "client-server"], "symptom": ["I'm trying to get my head around the ObjectInputStream/ObjectOutputStream, so I create a very simple server-client application where the client sends a HashMap object over the created stream and the server receives that and prints it out. ", "This my server code: -CODE-. ", "I run the server file and it runs ok. ", "Then I run the client file and I get the following error on the server: -CODE-. ", "I don't know if I have to do something to serialize the HashMap, but I think I saw somewhere that this is handled internally by Java. ", "EDIT after Aaron answer I implemented this part in my server as Aaron suggested: -CODE-. and now I get this error,again from server,after I run the client: -CODE-"], "exception_stack": ["    Exception in thread \"main\" java.net.SocketException: Connection reset\n    at java.net.SocketInputStream.read(SocketInputStream.java:189)\n    at java.net.SocketInputStream.read(SocketInputStream.java:121)\n    at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2308)\n    at java.io.ObjectInputStream$BlockDataInputStream.read(ObjectInputStream.java:2716)\n    at java.io.ObjectInputStream$BlockDataInputStream.readFully(ObjectInputStream.java:2740)\n    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1978)\n    at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:499)\n    at java.util.HashMap.readObject(HashMap.java:1115)\n    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n    at java.lang.reflect.Method.invoke(Method.java:606)\n    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)\n    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1891)\n    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1796)\n    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1348)\n    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)\n    at iotest.Server.main(Server.java:17)\nJava Result: 1\n", "Exception in thread \"main\" java.net.SocketException: Connection reset\n    at java.net.SocketInputStream.read(SocketInputStream.java:189)\n    at java.net.SocketInputStream.read(SocketInputStream.java:121)\n    at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2308)\n    at java.io.ObjectInputStream$BlockDataInputStream.read(ObjectInputStream.java:2716)\n    at java.io.ObjectInputStream$BlockDataInputStream.readFully(ObjectInputStream.java:2740)\n    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1978)\n    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1913)\n    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1796)\n    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1348)\n    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)\n    at java.util.HashMap.readObject(HashMap.java:1154)\n    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n    at java.lang.reflect.Method.invoke(Method.java:606)\n    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)\n    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1891)\n    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1796)\n    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1348)\n    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)\n    at iotest.Server.main(Server.java:17)\nJava Result: 1\n"], "code": ["import java.io.*;\nimport java.net.*;\n\npublic class Server {\n\n    public static void main(String[] args) throws IOException, ClassNotFoundException {\n        ServerSocket server = new ServerSocket(4444);\n        while (true) {\n            Socket socket = server.accept();\n            ObjectInputStream objIn = new ObjectInputStream(socket.getInputStream());\n\n            if (objIn.readObject() != null) {\n                System.out.println(objIn.readObject());\n            }\n        }    \n    }\n}\n", "import java.io.*;\nimport java.net.InetAddress;\nimport java.net.Socket;\nimport java.util.HashMap;\n\npublic class Client {\n\n    public static void main(String[] args) throws IOException {\n        Socket sock;\n        int port = 4444;\n        HashMap<Integer, String>  mapSend= new HashMap<>();\n        mapSend.put(1,\"row1\");\n        mapSend.put(2,\"row2\");\n\n        sock = new Socket(InetAddress.getLocalHost(), port);\n        ObjectOutputStream objOut = new ObjectOutputStream(sock.getOutputStream());\n\n        objOut.writeObject(mapSend);\n        objOut.flush();\n    }\n}\n", "Object objRead=objIn.readObject();\n            if (objRead != null) {\n                System.out.println(objRead);\n            }\n"], "exception_message_rank": 11, "title_rank": 5, "exception_message": "    Exception in thread \"main\" java.net.SocketException: Connection reset\n", "exception_message_score": 67}, {"answer_id": "32915964", "title": "Spring - RestTemplate Error calling a https rest service (Certificate error)", "Score": 1, "ViewCount": 38676, "LastEditDate": "2015-10-02 22:29:19", "LastActivityDate": "2015-10-06 12:47:06", "AnswerScore": 4, "reason": ["From your code i dont see any specific SSL configuration for your RestTemplate. ", "It requires HTTPClient 4.4. "], "solution": ["Since i dont know which version of Spring (and related HTTPClient), i suggest try starting with the following code and see what happens: -CODE-. ", "This should in theory bypass certs check. "], "answer_code": ["public void tryme() throws ClientProtocolException, IOException {\n String urlOverHttps = \"https:xxxxxxx\";  \n CloseableHttpClient httpClient = \n      HttpClients.custom()\n             .setSSLHostnameVerifier(new NoopHostnameVerifier())\n             .build();\n   HttpComponentsClientHttpRequestFactory reqFactory = \n              new HttpComponentsClientHttpRequestFactory();\n   reqFactory.setHttpClient(httpClient);\n\n   ResponseEntity<String> response =  \n          new RestTemplate(reqFactory).exchange(\n                  urlOverHttps, HttpMethod.GET, null, String.class);\n   String responseCode = response.getStatusCode();\n}\n"], "environment": ["rest", "ssl", "spring", "ssl-certificate", "tomcat war", "java"], "symptom": ["I call in tomcat war a rest web service. ", "I do the web service invocation with this: -CODE-. ", "The following error is produced when web service is called. ", "I try to do a lot of things but notting works: I think that the problem is with the certificate but i dont solve it. \u00bfDo you have any idea-CODE-"], "exception_stack": ["\norg.springframework.web.client.ResourceAccessException: I/O error on GET request for \"https://xxxxxxxxxxxxxxxxxxxxxxxx\":java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext); nested exception is java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)\n      at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:567)\n      at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:512)\n      at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:243)\n      at custom.service.usuarios.impl.UsuariosServiceImpl.validarDatosToken(UsuariosServiceImpl.java:69)\n      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n      at java.lang.reflect.Method.invoke(Method.java:606)\n      at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)\n      at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)\n      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)\n      at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)\n      at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)\n      at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)\n      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n      at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)\n      at com.sun.proxy.$Proxy33.validarDatosToken(Unknown Source)\n      at custom.view.filter.CustomAuthenticationProvider.authenticateReal(CustomAuthenticationProvider.java:48)\n      at custom.view.filter.CustomAuthenticationProvider.authenticate(CustomAuthenticationProvider.java:37)\n      at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:156)\n      at custom.view.filter.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:103)\n      at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:211)\n      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n      at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)\n      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n      at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)\n      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n      at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)\n      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n      at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)\n      at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)\n      at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)\n      at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)\n      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)\n      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)\n      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)\n      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)\n      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)\n      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)\n      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)\n      at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)\n      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)\n      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)\n      at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)\n      at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)\n      at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)\n      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n      at java.lang.Thread.run(Thread.java:745)\n  Caused by: java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)\n      at javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:198)\n      at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:205)\n      at sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:409)\n      at sun.net.NetworkClient.doConnect(NetworkClient.java:162)\n      at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)\n      at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)\n      at sun.net.www.protocol.https.HttpsClient.(HttpsClient.java:275)\n      at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)\n      at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)\n      at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)\n      at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)\n      at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)\n      at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:75)\n      at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)\n      at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)\n      at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:551)\n  Caused by: java.io.IOException: Invalid keystore format\n      at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:650)\n      at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:55)\n      at java.security.KeyStore.load(KeyStore.java:1214)\n      at sun.security.ssl.TrustManagerFactoryImpl.getCacertsKeyStore(TrustManagerFactoryImpl.java:221)\n      at sun.security.ssl.SSLContextImpl$DefaultSSLContext.getDefaultTrustManager(SSLContextImpl.java:528)\n      at sun.security.ssl.SSLContextImpl$DefaultSSLContext.(SSLContextImpl.java:495)\n      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)\n      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n      at java.lang.reflect.Constructor.newInstance(Constructor.java:526)\n      at java.security.Provider$Service.newInstance(Provider.java:1240)\n      ... 64 more\n"], "code": ["    public UsuarioDTO validarDatosToken(String token, boolean incluirRoles) throws ModeloException, DAOException {\n\n        RestTemplate restTemplate = new RestTemplate();\n        UserRestVO page = restTemplate.getForObject(\"https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"), UserRestVO.class);\n\n        if (page != null && page.getStatusResult() != null && page.getStatusResult().getStatusCode().equals(\"OK\") && page.getUser() != null) {\n            ------------\n            return datos;\n        } else {\n            throw new ModeloException(ErroresGeneralesEnum.ERROR_TOKEN_CADUCADO);\n        }\n    }\n}\n\n\npublic Authentication authenticateReal(Authentication authentication) throws AuthenticationException {\n\n    String username = authentication.getName();\n    String password = (String) authentication.getCredentials();\n\n    UsuarioDTO usuario = null;\n    try {\n        usuario = usuariosService.validarDatosToken(username, true);\n\n\n    } catch (Exception e) {\n        e.printStackTrace();\n        Logger.getLogger(CustomAuthenticationProvider.class.getName()).error(e);\n\n        throw new BadCredentialsException(\"Username not found.\");\n    }\n\n\n\n}\n"], "purpose": ["I call in tomcat war a rest web service. "], "purpose_rank": 6, "environment_rank": 23, "exception_stack_rank": 16, "exception_message": "org.springframework.web.client.ResourceAccessException: I/O error on GET request for \"https://xxxxxxxxxxxxxxxxxxxxxxxx\":java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext); nested exception is java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)\n  Caused by: java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)\n  Caused by: java.io.IOException: Invalid keystore format\n", "purpose_score": 82, "environment_score": 31, "exception_stack_score": 52}]}))
  })
  </script>
</body>

</html>